### ISSUE TITLE
No idea how to make a MongoDB query to fetch only the latest version of a package

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components-explorer#1]
@stubailo, @ekatek, any suggestions? [This is my current query](https://github.com/peerlibrary/meteor-blaze-components-explorer/blob/master/server/publish.coffee). The schema in [the documentation](https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API) does not look help

**Comment by mitar** [comment]
@tmeasday, how does Atmosphere know which version is latest?

**Comment by tmeasday** [comment]
Why not just use `version.published`?

**Comment by mitar** [comment]
Hmm. This still is not enough. Because MongoDB does not allow queries (without aggregations) where I could say that return me all version documents where `published` field is the newest, for the same package name.

I made now a complicated code which is updating another collection based on latest documents from version collection.

**Comment by tmeasday** [comment]
What were you hoping for though? You could denormalize `.isLatest` onto the version collection to make this query easier though..

**Comment by mitar** [comment]
What what? Where is `isLatest`???

**Comment by tmeasday** [comment]
Oh I just meant as you import versions you could run some logic to keep a (hypothetical) `isLatest` field up-to-date

**Comment by mitar** [comment]
Ah, yes. I am currently instead copying into a different collection. But good idea as well.

**Comment by mitar** [comment]
I made a package for the client: https://github.com/peerlibrary/meteor-packages

**Comment by stubailo** [comment]
Does the package implement the denormalization you were talking about?

**Comment by mitar** [comment]
It creates another collection where there are only latest versions of packages. So that is easy to query.
