### ISSUE TITLE
Unclear how to easily store package names which contain dots

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components-explorer#2]
As explained in [the documentation](https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API), and as observed in the database, you cannot store directly the output of the package server into the MongoDB. This is really sad because then it is hard to directly consume the API.

@stubailo, @ekatek, how is this done internally in Meteor? You are still using MongoDB, no? So you store documents differently than you are then publishing them? Why oh why.

@tmeasday, how does Atmosphere store stuff?

**Comment by stubailo** [comment]
> So you store documents differently than you are then publishing them? Why oh why.

Here's the story:
1. We used to not allow dots in package names
2. People really wanted that feature
3. Changing the entire schema of the package database was harder than just escaping the dots in the right places

So yeah, you can just have a function that replaces dots with `$` or something.

**Comment by mitar** [comment]
> People really wanted that feature

I know that people. ;-)

> So yeah, you can just have a function that replaces dots with $ or something.

So you escape before inserting, and unescaping before publishing? Really interesting. Why is that not done through EJSON?

**Comment by stubailo** [comment]
I don't think it really fits into the ejson model of custom data types, right? Since the problem is in key names. I guess the whole version map could be a data type. Perhaps it could be good to have a package that adds that type for ejson.

**Comment by mitar** [comment]
I decided to modify the schema when inserting into my database:

```
transformVersionDocument = (document) ->
  if document.dependencies
    document.dependencies = for packageName, dependency of document.dependencies
      _.extend dependency,
        packageName: packageName
  document
```

Also works better with MongoDB queries.

Now I just have to figure out #1.

**Comment by stubailo** [comment]
Yeah, I think this schema would have made more sense - using data as keys often results in issues like this when your data changes and starts having invalid symbols.

**Comment by tmeasday** [comment]
Yeah data as keys is a pain for a bunch of reasons (simple-schema doesn't like it for one thing). But it does make for simpler updates, so it's a two-edge sword.

PS This is what we do in atmosphere `key.replace(/\./g, '\uFF0E')`

**Comment by tmeasday** [comment]
(good times)
